[package]
name = "parse"
version = "0.1.0"
authors = ["Yuma Matsune <yuma.matsune@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0"
error = { path = "../error" }
span = { path = "../span" }
ast = { path = "../ast" }
lex = { path = "../lex" }
