[package]
name = "parse"
version = "0.1.0"
authors = ["Yuma Matsune <yuma.matsune@gmail.com>"]
edition = "2018"

[dependencies]
error = { path = "../error" }
pos = { path = "../pos" }
ast = { path = "../ast" }
lex = { path = "../lex" }
