[package]
name = "parse"
version = "0.1.0"
authors = ["Yuma Matsune <yuma.matsune@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0"
typed-arena = "2.0.1"
error = { path = "../error" }
pos = { path = "../pos" }
